#!/usr/bin/env python3
"""
Extract SML music tracks (bank-3 sequence data, RE'd from MusicStart_6AB5 +
the walker at $6CBE; format VALIDATED against PyBoy write-log captures of
track $07 -- ch2 = 77/77 note events matched in order, timing within 0.5
frames at 64Hz ticks). RULE 5: everything lands in gitignored build/audio/.

Song: SongTable_663C[track-1] -> header [b0][lentblptr][ch1][ch2][ch3][ch4].
Channel = list of 2-byte phrase pointers; control by entry HI byte (6C7F):
$FFxx = JUMP: the next word is a list address to continue from (the loop
point -- track 7 loops to entry 2: entry 1 is a play-once intro), $00xx =
END (one-shot jingles: the goal fanfare's ch1 stops the song). The stop
path (6CB1) kills the WHOLE song, so a channel list may lack a terminator
entirely (track $0F ch2 abuts phrase data): we end a list when it runs
into a known phrase/list address.
Phrase bytes: $00 next-phrase, $01 hold cell, $9D e d c = instrument
(e = GB NRx2 envelope, c = GB NRx1 duty), $A0-$AF = cell length := tbl[x]
(ticks @64Hz), even bytes = note: byte indexes NoteFreqTable_6E74 (2B LE).

Port encoding (music.bin):
  [0]        note table: 0x98 entries x 2B little-endian SV F (byte-index*2)
  per track: [16B length table][phrase blob][ch1 list][ch2 list]
  lists hold 16-bit offsets from music.bin start; $FFFF = restart marker.
music.inc: MUS_T<id>_L1/_L2 = list start offsets + mus_track_* tables.
"""
import os
ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "build", "audio")
d = open(os.path.join(ROOT, "super-mario-land-gb.gb"), "rb").read()
B = lambda gb: 3*0x4000 + (gb-0x4000)
u16 = lambda o: d[o] | (d[o+1] << 8)

TRACKS = [0x07, 0x04, 0x0C, 0x0F, 0x11, 0x12]   # level, underground, star, goal, hurry, bonus
NAMES  = ["MUS_LEVEL", "MUS_UNDER", "MUS_STAR", "MUS_GOAL", "MUS_HURRY", "MUS_BONUS"]

NT = B(0x6E74)
ntab = bytearray()
for i in range(0x98):
    x = d[NT+i] | (d[NT+i+1] << 8)
    if x >= 2048: F = 0
    else:
        hz = 131072.0 / (2048 - x)
        F = max(0, min(2047, int(round(125000.0/hz)) - 1))
    ntab += bytes([F & 0xFF, F >> 8])

out = bytearray(ntab)
inc = ["; GENERATED by tools/extract_music.py (build artifact)"]
track_l1, track_l2 = {}, {}
for tr in TRACKS:
    song = u16(B(0x663C) + (tr-1)*2)
    hdr = B(song)
    lentbl = u16(hdr+1)
    chp = [u16(hdr+3+i*2) for i in range(4)]
    ltab_off = len(out)
    out += bytes(d[B(lentbl):B(lentbl)+16])
    phrases, order = {}, []
    lists = []   # (entries, loop_ix or None)
    bounds = set(chp)
    for ch in range(2):                      # v1: GB ch1/ch2 -> SV squares
        base = chp[ch]; lp = B(base); lst = []; term = b"\x00\x00"; loop_ix = None
        while True:
            gbaddr = lp - 3*0x4000 + 0x4000
            if gbaddr != base and gbaddr in bounds:
                break
            p = u16(lp); lp += 2
            if (p >> 8) == 0x00:
                break
            if (p >> 8) == 0xFF:
                tgt = u16(lp)
                loop_ix = (tgt - base) // 2
                assert 0 <= loop_ix <= len(lst), f"list jump outside list: {tgt:04X}"
                break
            bounds.add(p)
            if p not in phrases:
                q = B(p); blob = bytearray()
                while True:
                    if q >= len(d) or len(blob) > 400:
                        raise SystemExit(f"RUNAWAY track ${tr:02X} ch{ch+1} phrase ${p:04X}: "
                                         + " ".join(f"{x:02X}" for x in d[B(p):B(p)+24]))
                    b = d[q]; q += 1
                    blob.append(b)
                    if b == 0: break
                    if b == 0x9D: blob += d[q:q+3]; q += 3
                phrases[p] = None; order.append(p)
            lst.append(p)
        lists.append((lst, loop_ix))
    poff = {}
    for p in order:
        q = B(p); blob = bytearray()
        while True:
            b = d[q]; q += 1
            blob.append(b)
            if b == 0: break
            if b == 0x9D: blob += d[q:q+3]; q += 3
        poff[p] = len(out); out += blob
    L = []
    for lst, loop_ix in lists:
        lbase = len(out)
        L.append(lbase)
        for p in lst:
            out += bytes([poff[p] & 0xFF, poff[p] >> 8])
        if loop_ix is None:
            out += b"\x00\x00"
        else:
            t = lbase + loop_ix*2
            out += b"\xFF\xFF" + bytes([t & 0xFF, t >> 8])
    track_l1[tr], track_l2[tr] = L
    inc.append(f"MUS_T{tr:02X}_LT = {ltab_off}")
    print(f"track ${tr:02X}: lentab@{ltab_off} lists@{L} ({len(order)} phrases)")

inc.append(f"MUS_NTRACKS = {len(TRACKS)}")
for i, nm in enumerate(NAMES):
    inc.append(f"{nm} = {i}")
inc.append("mus_track_ids: .byte " + ", ".join(f"${t:02X}" for t in TRACKS))
for nm, tab in (("l1", track_l1), ("l2", track_l2)):
    inc.append(f"mus_{nm}_lo: .byte " + ", ".join(f"<{tab[t]}" for t in TRACKS))
    inc.append(f"mus_{nm}_hi: .byte " + ", ".join(f">{tab[t]}" for t in TRACKS))
inc.append("mus_lt_lo: .byte " + ", ".join(f"<MUS_T{t:02X}_LT" for t in TRACKS))
inc.append("mus_lt_hi: .byte " + ", ".join(f">MUS_T{t:02X}_LT" for t in TRACKS))
os.makedirs(OUT, exist_ok=True)
open(os.path.join(OUT, "music.bin"), "wb").write(bytes(out))
open(os.path.join(OUT, "music.inc"), "w").write("\n".join(inc) + "\n")
print(f"music.bin: {len(out)} bytes total")
