#!/usr/bin/env python3
"""
Generate build/w2abi.inc: engine-symbol equates for the standalone W2 overlay
build (src/w2code.s). The overlay is assembled AFTER the main link against the
addresses in its debug info, so it can call engine code and share its zero
page / BSS -- the same trick the GB uses for banked code, done at build time.

Usage: gen_w2abi.py <dbgfile> <out.inc>
"""
import re, sys

NEED = [
    "x_step",
    "quad16",
    "pair16",
    "mario_facing",
    "fall_v",
    "arc_idx",
    "jump_state",
    "victim_xy",
    "blit_behind",
    "w3_spawn_at",
    "award_stomp",
    # the vector block + the level binding
    "ovl_vec", "hdr_buf", "cur_level",
    # object slots (SoA)
    "o_type", "o_xl", "o_xh", "o_y", "o_vx", "o_vy", "o_tmr",
    "o_pvx", "o_pvy", "o_pdr", "o_st", "o_pw", "o_pfr", "o_hp",
    # spawning
    "spawn_tab", "find_free_obj", "obj_alloc_typed", "spawn_tabx",
    # world state
    "cam_x", "spr_x", "spr_y", "mario_big", "frame_count", "oi",
    "hurt_inv", "mario_grow", "mario_shrink",   # sub_off must mirror hurt_mario's
                                                # "this hit is thrown away" guard
    # drawing
    "draw_quad", "draw_tile_yflip", "dcol", "dy", "spr_subx", "do_flip",
    # combat / scoring
    "award_kill_at", "tmpL2", "tmpH2", "tmpH3", "tmpL", "tmpH",
    # sfx
    "sfx_play",
    # shared-kit dependencies (the kit_sh*.inc bodies)
    "mario_dx", "rc_wball_aim", "rc_wball_move", "tmpL3", "mario_starT", "award_kill", "l3_above", "hurt_mario",
    "ride", "carry_y_up", "spawn_item_snd", "obj_set_x8", "mrow", "spr_col", "mark_used", "read_solid", "feet_col",
    # 2-3 Marine Pop (kit_mar23.inc): the vehicle player + torpedoes
    "veh_vec", "pad_held", "pad_pressed", "goal_phase", "goal_tmr", "goal_top",
    "death_anim",                               # veh_step: detect a respawn
    "mus_rate", "mus_stop", "mus_start", "cam_max", "mod_test", "mod_set",
    "ending13", "e_cap", "mario_frame", "quad_cols", "quad_rows",
    # W3 (docs/33): the window map reader + the stub
    "map_ptr", "map_base", "lvl_cols", "mc_colh", "mc_coll", "mc_row",
    "mapread_vec", "w3_pc", "w3_ti", "w3_ph0", "w3_ph1", "w3_fcc", "do_yflip", "flipbuf", "w3_ffc7", "w3_stand", "w3_carry_rt", "w3_carry_lf", "w3_cinval", "set_dst", "dst_ptr", "src_ptr", "p_shlo", "p_shhi",
    "map_transform", "map_offmap",
    "wcol", "redraw_one", "award_coin", "hit_qblock", "break_brick",
    "restore_bg", "rb_vx", "rb_y", "rb_cols", "rb_rows",
    "read_map_tile", "add_score", "calc_feet_col", "fb_col0", "mario_vx", "scroll_s", "bud_base", "find_block", "spawn_walker", "spawn_flower", "spawn_star",
    # kit constants live in code, not symbols -- redefined in w2code.s
]

def main():
    dbg, out = sys.argv[1], sys.argv[2]
    d = open(dbg).read()
    lines = ["; GENERATED by tools/gen_w2abi.py -- engine addresses for the W2 overlay"]
    missing = []
    for n in NEED:
        m = re.search(r'sym\tid=\d+,name="%s",addrsize=\w+,[^\n]*val=(0x[0-9A-Fa-f]+)' % re.escape(n), d)
        if not m:
            missing.append(n)
            continue
        lines.append("%-16s = $%04X" % (n, int(m.group(1), 16)))
    if missing:
        sys.exit("gen_w2abi: missing symbols: %s" % missing)
    open(out, "w").write("\n".join(lines) + "\n")
    print("w2abi.inc: %d symbols" % (len(lines) - 1))

if __name__ == "__main__":
    main()
