#!/usr/bin/env python3
"""
Generate build/w2abi.inc: engine-symbol equates for the standalone W2 overlay
build (src/w2code.s). The overlay is assembled AFTER the main link against the
addresses in its debug info, so it can call engine code and share its zero
page / BSS -- the same trick the GB uses for banked code, done at build time.

Usage: gen_w2abi.py <dbgfile> <out.inc>
"""
import re, sys

NEED = [
    "x_step",
    "quad16",
    "pair16",
    "mario_facing",
    "fall_v",
    "arc_idx",
    "jump_state",
    "victim_xy",
    "award_stomp",
    # the vector block + the level binding
    "ovl_vec", "hdr_buf", "cur_level",
    # object slots (SoA)
    "o_type", "o_xl", "o_xh", "o_y", "o_vx", "o_vy", "o_tmr",
    "o_pvx", "o_pvy", "o_pdr", "o_st", "o_pw", "o_pfr", "o_hp",
    # spawning
    "spawn_tab", "find_free_obj", "obj_alloc_typed", "spawn_tabx",
    # world state
    "cam_x", "spr_x", "spr_y", "mario_big", "frame_count", "oi",
    # drawing
    "draw_quad", "draw_tile_yflip", "dcol", "dy", "spr_subx", "do_flip",
    # combat / scoring
    "award_kill_at", "tmpL2", "tmpH2", "tmpH3", "tmpL", "tmpH",
    # sfx
    "sfx_play",
    # shared-kit dependencies (the kit_sh*.inc bodies)
    "mario_dx", "rc_wball_aim", "rc_wball_move", "tmpL3", "mario_starT", "award_kill", "l3_above", "hurt_mario",
    "ride", "carry_y_up", "spawn_item_snd", "obj_set_x8", "mrow", "spr_col", "mark_used",
    # kit constants live in code, not symbols -- redefined in w2code.s
]

def main():
    dbg, out = sys.argv[1], sys.argv[2]
    d = open(dbg).read()
    lines = ["; GENERATED by tools/gen_w2abi.py -- engine addresses for the W2 overlay"]
    missing = []
    for n in NEED:
        m = re.search(r'sym\tid=\d+,name="%s",addrsize=\w+,[^\n]*val=(0x[0-9A-Fa-f]+)' % re.escape(n), d)
        if not m:
            missing.append(n)
            continue
        lines.append("%-16s = $%04X" % (n, int(m.group(1), 16)))
    if missing:
        sys.exit("gen_w2abi: missing symbols: %s" % missing)
    open(out, "w").write("\n".join(lines) + "\n")
    print("w2abi.inc: %d symbols" % (len(lines) - 1))

if __name__ == "__main__":
    main()
