#!/usr/bin/env python3
"""Emit the unique-column-pool form of 1-2's map (docs/33) as assembly for
leveldata.s: a .addr pointer table (2B/col) + labeled 16-byte pool columns.
The linker resolves the absolute addresses. RULE 5: reads/writes only
gitignored build artifacts."""
import sys

src, out = sys.argv[1], sys.argv[2]
m = open(src, "rb").read()
assert len(m) % 16 == 0
cols = len(m) // 16
index = {}
order = []
refs = []
for c in range(cols):
    col = m[c * 16:(c + 1) * 16]
    if col not in index:
        index[col] = len(order)
        order.append(col)
    refs.append(index[col])

with open(out, "w") as f:
    f.write(f"; generated by gen_dedup_inc.py from {src}: {cols} cols, "
            f"{len(order)} unique\n")
    f.write(f"L12_COLS = {cols}\n")
    f.write("level0_map:\n")
    for i in range(0, cols, 8):
        f.write("    .addr " + ", ".join(f"l12c{r}" for r in refs[i:i + 8]) + "\n")
    for i, col in enumerate(order):
        f.write(f"l12c{i}: .byte " + ",".join(f"${b:02X}" for b in col) + "\n")
print(f"gen_dedup_inc: {cols} cols -> {len(order)} unique "
      f"({cols*2 + len(order)*16} bytes, raw {len(m)})")
