#!/usr/bin/env python3
"""emit build/w3auxabi.inc: the aux page's entry points for the kit."""
import re
l = open('build/w3aux.lbl').read()
syms = {n: a for a, n in re.findall(r'al 00([0-9A-F]{4}) \.(aux_group|aux_sweep)$', l, re.M)}
with open('build/w3auxabi.inc', 'w') as f:
    f.write('; GENERATED by gen_w3auxabi.py -- the aux page entry points (docs/42)\n')
    for n, a in sorted(syms.items()):
        f.write(f'{n} = ${a}\n')
print(f"gen_w3auxabi: {', '.join(f'{n}=${a}' for n, a in sorted(syms.items()))}")
