#!/usr/bin/env python3
"""Extract the World-3 enemy AI scripts + metasprite display lists from the
user's ROM for the port's AI-VM (docs/34).

Emits:
  build/w3scripts.bin   raw script bytes, concatenated (packed into bank 6)
  build/w3data.inc      assembly: the type table, per-type script offsets, and
                        the metasprite display lists (they live in the kit's
                        RAM window; the scripts stay in bank 6)

RULE 5: reads the ROM only as a build input; every output is gitignored.
"""
import sys, os

ROM = open(sys.argv[1] if len(sys.argv) > 1 else "super-mario-land-gb.gb", "rb").read()
OUT_BIN = "build/w3scripts.bin"
OUT_INC = "build/w3data.inc"
SCRIPT_TBL = 0x349E                       # AIScriptPtrTable, 99 entries
DL_RIGHT, DL_LEFT = 0x2FE2, 0x30B4        # metasprite display lists
PHYS_TBL = 0x3375                         # 3 bytes per type
CONTACT_TBL = 0x3186                      # 5 bytes per type; +0 = the STOMP result
                                          # (0 = not stompable: the GB's stomp test
                                          # at $08C7 reads this column)

# every GB type W3's spawn lists name (types the ENGINE already handles --
# $00/$04/$0A/$0B/$0E/$36 -- and the shared kit types $02/$0C are excluded)
SEED = [0x03, 0x05, 0x25, 0x31, 0x32, 0x35, 0x38, 0x39,
        0x3A, 0x3B, 0x3C, 0x47, 0x49, 0x56]


def flat(addr):
    """script/display-list pointers are bank-0/1 flat in the first 32K"""
    return addr


def script_bytes(t):
    p = SCRIPT_TBL + t * 2
    a = ROM[p] | (ROM[p + 1] << 8)
    off = flat(a)
    i, n = off, 0
    while n < 240:
        b = ROM[i]
        if b == 0xFF:
            return ROM[off:i + 1]          # keep the $FF (loop-to-start)
        i += 2 if 0xF0 <= b <= 0xFE else 1
        n += 1
    raise SystemExit(f"script ${t:02X}: no terminator")


def dlist(param, base):
    p = base + param * 2
    a = ROM[p] | (ROM[p + 1] << 8)
    off = flat(a)
    i = off
    while ROM[i] != 0xFF and i - off < 48:
        i += 1
    return ROM[off:i + 1]


def main():
    # transitive closure over morph ($F3) / spawn-child ($F1) targets
    types, todo = [], list(SEED)
    params = set()
    while todo:
        t = todo.pop(0)
        if t in types or t > 0x7F:
            continue
        types.append(t)
        for c in range(5):                    # contact results are types too
            r = ROM[CONTACT_TBL + 5 * t + c]  # (stomp/ball/star chains)
            if 0 < r <= 0x7F:
                todo.append(r)
        b = script_bytes(t)
        i = 0
        while i < len(b):
            op = b[i]
            if 0xF0 <= op <= 0xFE:
                arg = b[i + 1] if i + 1 < len(b) else 0
                if op == 0xF8:
                    params.add(arg)
                if op in (0xF1, 0xF3) and arg <= 0x7F:
                    todo.append(arg)          # morph / spawn-child targets
                i += 2
            else:
                i += 1
    types.sort()
    params = sorted(params)

    blob = bytearray()
    offs = {}
    for t in types:
        offs[t] = len(blob)
        blob += script_bytes(t)
    os.makedirs("build", exist_ok=True)
    open(OUT_BIN, "wb").write(bytes(blob))

    with open(OUT_INC, "w") as f:
        f.write("; generated by tools/gen_w3data.py -- W3 AI-VM data (docs/34)\n")
        f.write(f"W3_NTYPES = {len(types)}\n")
        f.write(f"W3_SCRIPTS_LEN = {len(blob)}\n")
        f.write("; GB type id per VM index\n")
        f.write("w3_typetab:\n    .byte " + ",".join(f"${t:02X}" for t in types) + "\n")
        f.write("; script offset within the bank-6 blob, per VM index\n")
        f.write("w3_scrlo:\n    .byte " + ",".join(f"<{offs[t]}" for t in types) + "\n")
        f.write("w3_scrhi:\n    .byte " + ",".join(f">{offs[t]}" for t in types) + "\n")
        f.write("; PhysicsParamTable rows: [0] = the COLLISION-RESPONSE flags the VM\n")
        f.write("; reads as ffc7 ($30 -> restart the script on landing, etc.)\n")
        f.write("w3_phys0:\n    .byte " + ",".join(f"${ROM[PHYS_TBL+3*t]:02X}" for t in types) + "\n")
        f.write("w3_phys1:\n    .byte " + ",".join(f"${ROM[PHYS_TBL+3*t+1]:02X}" for t in types) + "\n")
        f.write("w3_phys2:\n    .byte " + ",".join(f"${ROM[PHYS_TBL+3*t+2]:02X}" for t in types) + "\n")
        f.write("; contact table $3186 column +0: the type to MORPH INTO when\n")
        f.write("; stomped ($00 = not stompable -- Mario passes through the head)\n")
        f.write("w3_stomp:\n    .byte " + ",".join(f"${ROM[CONTACT_TBL+5*t]:02X}" for t in types) + "\n")
        # display lists: index by param through a compact table
        f.write(f"W3_NPARAM = {len(params)}\n")
        f.write("w3_paramtab:\n    .byte " + ",".join(f"${p:02X}" for p in params) + "\n")
        # COMPACT tile slice: the lists reference GB overlay tiles $A0-$DC;
        # ship only the ones actually drawn, renumbered to a contiguous port
        # range from $A0 (draw_quad resolves $A0-$DC through the header's
        # overlay base). Tiles < $A0 come from the shared chardata sheet and
        # keep their GB ids.
        order, remap = [], {}
        def conv(lst):
            out = bytearray()
            for b in lst:
                if b & 0x80 and b != 0xFF and 0xA0 <= b <= 0xDC:
                    if b not in remap:
                        remap[b] = 0xA0 + len(order)
                        order.append(b)
                    out.append(remap[b])
                else:
                    out.append(b)
            return out
        body = bytearray()
        starts, startsL = [], []
        for p in params:                      # RIGHT list then LEFT list
            starts.append(len(body));  body += conv(dlist(p, DL_RIGHT))
        for p in params:
            startsL.append(len(body)); body += conv(dlist(p, DL_LEFT))
        open("build/w3tiles.txt", "w").write(" ".join(f"{t:02X}" for t in order))
        assert len(order) <= 0x3D, "W3 tile slice exceeds the $A0-$DC window"
        f.write("; display lists live in BANK 6 at W3DLB (pack_banks pin)\n")
        f.write("w3_dlo:\n    .byte " + ",".join(f"<(W3DLB+{s})" for s in starts) + "\n")
        f.write("w3_dhi:\n    .byte " + ",".join(f">(W3DLB+{s})" for s in starts) + "\n")
        f.write("w3_dloL:\n    .byte " + ",".join(f"<(W3DLB+{s})" for s in startsL) + "\n")
        f.write("w3_dhiL:\n    .byte " + ",".join(f">(W3DLB+{s})" for s in startsL) + "\n")
        open("build/w3dlists.bin", "wb").write(bytes(body))
    print(f"gen_w3data: {len(types)} scripts ({len(blob)}B), {len(params)} params "
          f"({len(body)}B lists), {len(order)} tiles -> {OUT_INC}")


if __name__ == "__main__":
    main()
